---
title: "Weight Lifting Exercise Prediction"
subtitle: "Practicle Machine Learning Course Project"
author: "Brian Gulbis"
date: "August 16, 2015"
output: 
  html_document: 
    fig_caption: yes
    keep_md: yes
---

```{r}
library(dplyr)
library(lubridate)
library(caret)
```


```{r warning=FALSE}
training <- read.csv("pml-training.csv", stringsAsFactors = FALSE) %>%
    mutate(cvtd_timestamp = dmy_hm(cvtd_timestamp),
           user_name = factor(user_name),
           new_window = factor(new_window),
           classe = factor(classe)) %>%
    rename(max_pitch_belt = max_picth_belt,
           kurtosis_pitch_belt = kurtosis_picth_belt,
           kurtosis_pitch_arm = kurtosis_picth_arm,
           max_pitch_arm = max_picth_arm,
           max_pitch_dumbbell = max_picth_dumbbell,
           kurtosis_pitch_forearm = kurtosis_picth_forearm,
           max_pitch_forearm = max_picth_forearm) %>%
    mutate_each(funs(as.numeric), kurtosis_roll_belt:magnet_forearm_z)
```

```{r}
library(rpart)
near.zero <- nearZeroVar(training, saveMetrics = TRUE)
nz <- training[,near.zero$zeroVar == FALSE]
modelTree <- train(classe ~ ., method="rpart", data=nz[,8:151])
```

```{r}
modelRF <- train(classe ~ ., method="rf", data=nz[,8:151])
```


```{r warning=FALSE}
near.zero <- nearZeroVar(training, saveMetrics = TRUE)
nz <- training[,near.zero$zeroVar == FALSE]
preProc <- preProcess(nz[,8:150], method="pca", pcaComp=5)
trainPCA <- predict(preProc, nz[,8:150])
modelFit <- train(training$classe ~ ., method="glm", data=trainPCA)
```

